In [1]:
import numpy as np
import random

In [2]:
# 1. prints vector of numbers from 12 to 42
vect_from_12_to_42 = np.arange(12, 43, 1)
vect_from_12_to_42

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [3]:
# 2. print vector of 12 zeros with "1" in 5th place
vect_zeros_and_one = np.zeros(12)
vect_zeros_and_one[4] = 1
vect_zeros_and_one

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 3. print 3x3 matrix from 0 to 8
matrix_from_0_to_8 = (np.arange(0, 9, 1)).reshape(3, 3)
matrix_from_0_to_8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# 4. finds all positive numbers from np.array([1,2,0,0,4,0])
arr4 = np.array([1,2,0,0,4,0])
ans4 = []
for item in arr4:
    if item > 0:
        ans4.append(item)
ans4

[1, 2, 4]

In [6]:
# 5. multiplies matrix 5x3 to matrix 3x2
matrix1 = np.random.randint(0, 10, size=(5, 3))
matrix2 = np.random.randint(0, 10, size=(3, 2))
matrix5 = np.dot(matrix1, matrix2)

matrix5

array([[32, 68],
       [32, 66],
       [24, 39],
       [18, 37],
       [ 8,  0]])

In [7]:
# 6. prints matrix with "0" on edges and "1" inside
matrix_ans_6 = np.ones((10, 10), dtype=np.int64)
matrix_ans_6[0, :] = 0
matrix_ans_6[9, :] = 0
matrix_ans_6[:, 0] = 0
matrix_ans_6[:, 9] = 0

matrix_ans_6


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [8]:
# 7. sorting random vector
random_vector = np.random.randint(100, size=(10))
np.sort(random_vector)

array([10, 14, 17, 41, 46, 56, 58, 79, 92, 94])

In [9]:
# 8. equivalent of "enumerate" for numpy
# np.ndenumerate

In [10]:
# 9. calculate mean and standard deviation of vector 
vect_9 = np.random.randint(0, 10, size=(10, 1))
print(f"initial vector is \n {vect_9}")
mean_vect_9 = np.mean(vect_9)
print(f"mean of initial vector is {mean_vect_9}")
vect_mean = vect_9[:]
vect_mean = vect_mean - mean_vect_9
print(f"vector subtracted mean is {vect_mean}")

std_vect = np.std(vect_9)
print(f"standard deviation of initial vector is {std_vect}")

initial vector is 
 [[0]
 [8]
 [8]
 [6]
 [7]
 [4]
 [0]
 [3]
 [8]
 [5]]
mean of initial vector is 4.9
vector subtracted mean is [[-4.9]
 [ 3.1]
 [ 3.1]
 [ 1.1]
 [ 2.1]
 [-0.9]
 [-4.9]
 [-1.9]
 [ 3.1]
 [ 0.1]]
standard deviation of initial vector is 2.947880594596735


In [11]:
# 10. find the closest number from vector
random_vect10 = np.random.randint(0, 100, size=15)
n = random.randint(0, 100)
ans10 = random_vect10[0]
difference = abs(random_vect10[0] - n)

for item in random_vect10:
    if abs(item - n) < difference:
        difference = abs(item - n)
        ans10 = item
item

19

In [12]:
# 11. find last N highest numbers
n = 10
random_vector = (np.sort(np.random.randint(100, size=(10, 10)).reshape(100)))

random_vector[-n:]

array([90, 91, 91, 92, 96, 97, 98, 98, 99, 99])